
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.5
  creationTimestamp: null
  name: hncconfigurations.hnc.x-k8s.io
spec:
  group: hnc.x-k8s.io
  names:
    kind: HNCConfiguration
    listKind: HNCConfigurationList
    plural: hncconfigurations
    singular: hncconfiguration
  scope: Cluster
  validation:
    openAPIV3Schema:
      description: HNCConfiguration is a cluster-wide configuration for HNC as a whole.
        See details in http://bit.ly/hnc-type-configuration
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: HNCConfigurationSpec defines the desired state of HNC configuration.
          properties:
            types:
              description: Types indicates the desired synchronization states of kinds,
                if any.
              items:
                description: TypeSynchronizationSpec defines the desired synchronization
                  state of a specific kind.
                properties:
                  apiVersion:
                    description: API version of the kind defined below. This is used
                      to unambiguously identifies the kind.
                    type: string
                  kind:
                    description: Kind to be configured.
                    type: string
                  mode:
                    description: Synchronization mode of the kind. If the field is
                      empty, it will be treated as "propagate". An unsupported mode
                      will be treated as "ignore".
                    type: string
                type: object
              type: array
          type: object
        status:
          description: HNCConfigurationStatus defines the observed state of HNC configuration.
          properties:
            conditions:
              description: Conditions describes the errors, if any.
              items:
                description: HNCConfigurationCondition specifies the code and the
                  description of an error condition.
                properties:
                  code:
                    description: "Describes the condition in a machine-readable string
                      value. The currently valid values are shown below, but new values
                      may be added over time. This field is always present in a condition.
                      \n All codes that begin with the prefix `crit` indicate that
                      reconciliation has been paused for this configuration. Future
                      changes of the configuration will be ignored by HNC until the
                      condition has been resolved. Non-critical conditions typically
                      indicate some kinds of error that HNC itself can ignore. However,
                      the behaviors of some types might be out-of-sync with the users'
                      expectations. \n Currently, the supported values are: \n - \"critSingletonNameInvalid\":
                      the specified singleton name is invalid. The name should be
                      the same as HNCConfigSingleton. \n - \"objectReconcilerCreationFailed\":
                      an error exists when creating the object reconciler for the
                      type specified in Msg. \n - \"multipleConfigurationsForOneType\":
                      Multiple configurations exist for the type specified in the
                      Msg. One type should only have one configuration."
                    type: string
                  msg:
                    description: A human-readable description of the condition, if
                      the `code` field is not sufficiently clear on their own. If
                      the condition is only for specific types, Msg will include information
                      about the types (e.g., GVK).
                    type: string
                required:
                - code
                type: object
              type: array
            types:
              description: Types indicates the observed synchronization states of
                kinds, if any.
              items:
                description: TypeSynchronizationStatus defines the observed synchronization
                  state of a specific kind.
                properties:
                  apiVersion:
                    description: API version of the kind defined below. This is used
                      to unambiguously identifies the kind.
                    type: string
                  kind:
                    description: Kind to be configured.
                    type: string
                  numPropagated:
                    description: Tracks the number of original objects that are being
                      propagated to descendant namespaces.
                    format: int32
                    minimum: 0
                    type: integer
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
