
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.8
  creationTimestamp: null
  name: hncconfigurations.hnc.x-k8s.io
spec:
  group: hnc.x-k8s.io
  names:
    kind: HNCConfiguration
    listKind: HNCConfigurationList
    plural: hncconfigurations
    singular: hncconfiguration
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HNCConfiguration is a cluster-wide configuration for HNC as a whole. See details in http://bit.ly/hnc-type-configuration
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            # This is patched by hack/crd_patches/singleton-enum-patch.sh
            properties:
              name:
                type: string
                enum:
                  - config
            type: object
          spec:
            description: HNCConfigurationSpec defines the desired state of HNC configuration.
            properties:
              types:
                description: Types indicates the desired synchronization states of kinds, if any.
                items:
                  description: TypeSynchronizationSpec defines the desired synchronization state of a specific kind.
                  properties:
                    apiVersion:
                      description: API version of the kind defined below. This is used to unambiguously identifies the kind.
                      type: string
                    kind:
                      description: Kind to be configured.
                      type: string
                    mode:
                      description: Synchronization mode of the kind. If the field is empty, it will be treated as "propagate".
                      enum:
                      - propagate
                      - ignore
                      - remove
                      type: string
                  required:
                  - apiVersion
                  - kind
                  type: object
                type: array
            type: object
          status:
            description: HNCConfigurationStatus defines the observed state of HNC configuration.
            properties:
              conditions:
                description: Conditions describes the errors, if any.
                items:
                  description: HNCConfigurationCondition specifies the code and the description of an error condition.
                  properties:
                    code:
                      description: "Describes the condition in a machine-readable string value. The currently valid values are shown below, but new values may be added over time. This field is always present in a condition. \n Conditions typically indicate some kinds of error that HNC itself can ignore. However, the behaviors of some types might be out-of-sync with the users' expectations. \n Currently, the supported values are: \n - \"objectReconcilerCreationFailed\": an error exists when creating the object reconciler for the type specified in Msg. \n - \"multipleConfigurationsForOneType\": Multiple configurations exist for the type specified in the Msg. One type should only have one configuration."
                      type: string
                    msg:
                      description: A human-readable description of the condition, if the `code` field is not sufficiently clear on their own. If the condition is only for specific types, Msg will include information about the types (e.g., GVK).
                      type: string
                  required:
                  - code
                  type: object
                type: array
              namespaceConditions:
                description: NamespaceConditions is a map of namespace condition codes to the namespaces affected by those codes. If HNC is operating normally, no conditions will be present; if there are any conditions beginning with the "Crit" (critical) prefix, this means that HNC cannot function in the affected namespaces. The HierarchyConfiguration object in each of the affected namespaces will have more information. To learn more about conditions, see https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/concepts.md#admin-conditions.
                items:
                  properties:
                    code:
                      description: Code is a namespace condition code
                      type: string
                    namespaces:
                      description: Namespaces is the list of namespaces affected by this code
                      items:
                        type: string
                      type: array
                  required:
                  - code
                  - namespaces
                  type: object
                type: array
              types:
                description: Types indicates the observed synchronization states of kinds, if any.
                items:
                  description: TypeSynchronizationStatus defines the observed synchronization state of a specific kind.
                  properties:
                    apiVersion:
                      description: API version of the kind defined below. This is used to unambiguously identifies the kind.
                      type: string
                    kind:
                      description: Kind to be configured.
                      type: string
                    mode:
                      description: Mode describes the synchronization mode of the kind. Typically, it will be the same as the mode in the spec, except when the reconciler has fallen behind or when the mode is omitted from the spec and the default is chosen.
                      type: string
                    numPropagatedObjects:
                      description: Tracks the number of objects that are being propagated to descendant namespaces. The propagated objects are created by HNC.
                      minimum: 0
                      type: integer
                    numSourceObjects:
                      description: Tracks the number of objects that are created by users.
                      minimum: 0
                      type: integer
                  required:
                  - apiVersion
                  - kind
                  type: object
                type: array
            type: object
        type: object
    served: false
    storage: false
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: HNCConfiguration is a cluster-wide configuration for HNC as a whole. See details in http://bit.ly/hnc-type-configuration
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            # This is patched by hack/crd_patches/singleton-enum-patch.sh
            properties:
              name:
                type: string
                enum:
                  - config
            type: object
          spec:
            description: HNCConfigurationSpec defines the desired state of HNC configuration.
            properties:
              types:
                description: Types indicates the desired synchronization states of kinds, if any.
                items:
                  description: TypeSynchronizationSpec defines the desired synchronization state of a specific kind.
                  properties:
                    apiVersion:
                      description: API version of the kind defined below. This is used to unambiguously identifies the kind.
                      type: string
                    kind:
                      description: Kind to be configured.
                      type: string
                    mode:
                      description: Synchronization mode of the kind. If the field is empty, it will be treated as "Propagate".
                      enum:
                      - Propagate
                      - Ignore
                      - Remove
                      type: string
                  required:
                  - apiVersion
                  - kind
                  type: object
                type: array
            type: object
          status:
            description: HNCConfigurationStatus defines the observed state of HNC configuration.
            properties:
              conditions:
                description: Conditions describes the errors, if any.
                items:
                  description: HNCConfigurationCondition specifies the code and the description of an error condition.
                  properties:
                    code:
                      description: "Describes the condition in a machine-readable string value. The currently valid values are shown below, but new values may be added over time. This field is always present in a condition. \n Conditions typically indicate some kinds of error that HNC itself can ignore. However, the behaviors of some types might be out-of-sync with the users' expectations. \n Currently, the supported values are: \n - \"objectReconcilerCreationFailed\": an error exists when creating the object reconciler for the type specified in Msg. \n - \"multipleConfigurationsForOneType\": Multiple configurations exist for the type specified in the Msg. One type should only have one configuration."
                      type: string
                    msg:
                      description: A human-readable description of the condition, if the `code` field is not sufficiently clear on their own. If the condition is only for specific types, Msg will include information about the types (e.g., GVK).
                      type: string
                  required:
                  - code
                  type: object
                type: array
              namespaceConditions:
                description: NamespaceConditions is a map of namespace condition types and reasons to the affected namespaces. If HNC is operating normally, no conditions will be present; if there are any conditions with "ActivitiesHalted" type, this means that HNC cannot function in the affected namespaces. The HierarchyConfiguration object in each of the affected namespaces will have more information. To learn more about conditions, see https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/docs/user-guide/concepts.md#admin-conditions.
                items:
                  properties:
                    namespaces:
                      description: Namespaces is the list of namespaces affected by this code
                      items:
                        type: string
                      type: array
                    reason:
                      description: Reason is a namespace condition reason
                      type: string
                    type:
                      description: Type is a namespace condition type
                      type: string
                  required:
                  - namespaces
                  - reason
                  - type
                  type: object
                type: array
              types:
                description: Types indicates the observed synchronization states of kinds, if any.
                items:
                  description: TypeSynchronizationStatus defines the observed synchronization state of a specific kind.
                  properties:
                    apiVersion:
                      description: API version of the kind defined below. This is used to unambiguously identifies the kind.
                      type: string
                    kind:
                      description: Kind to be configured.
                      type: string
                    mode:
                      description: Mode describes the synchronization mode of the kind. Typically, it will be the same as the mode in the spec, except when the reconciler has fallen behind or when the mode is omitted from the spec and the default is chosen.
                      type: string
                    numPropagatedObjects:
                      description: Tracks the number of objects that are being propagated to descendant namespaces. The propagated objects are created by HNC.
                      minimum: 0
                      type: integer
                    numSourceObjects:
                      description: Tracks the number of objects that are created by users.
                      minimum: 0
                      type: integer
                  required:
                  - apiVersion
                  - kind
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
