# # cluster admin kubeconfig file
# adminKubeconfig: 

# # the tenant kubeconfig and its namespace
# tenantA:
#   kubeconfig: 
#   namespace: 

# # the tenant kubeconfig and its namespace
# tenantB:
#   kubeconfig: 
#   namespace: 

# # label is used to identify the resources 
# # managed by the cluster administrator
# label: