apiVersion: tenancy.x-k8s.io/v1alpha1
kind: VirtualCluster
metadata: 
  labels:
    controller-tools.k8s.io: "1.0"
  name: vc-sample-1
  namespace: tenant1admin
spec:
  clusterDomain: cluster.local
  clusterVersionName: cv-sample-np
  # will expire in one year
  pkiExpireDays: 365
  opaqueMetaPrefixes:
    - "tenancy.x-k8s.io"
  transparentMetaPrefixes:
    - "k8s.net.status"
